name: Update Answers

on:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours
  workflow_dispatch:
    branches:
      - main

jobs:
  answer:
    name: "Run answer scrapers"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Run Script
        run: |
          pnpm install --frozen-lockfile
          pnpm run answer
      - name: Commit
        run: |
          git config user.name "Liuming Chen"
          git config user.email "51524534+let-lc@users.noreply.github.com"
          git add ./data/answers.json
          git commit -m "github action: answer update" || echo "No new answer."
          git push
